# arguments for dataset
dataset: cityscapes
nclass: 19
crop_size: 801
data_root: /ST1//0_program/SSSS/cityspace/


# arguments for training
epochs: 240
batch_size: 2
lr: 0.005  
lr_multi: 1.0
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 100000
conf_thresh: 0.0

# arguments for model
backbone: resnet50
multi_grid: True
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
